// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AttachMediaPath stores a dropped image/video and returns its inline HTML.
 * Non-media files return "" so the caller can fall back to the chip list.
 */
export function AttachMediaPath(noteID: number, path: string): $CancellablePromise<string> {
    return $Call.ByID(2512589376, noteID, path);
}

/**
 * AttachMediaViaDialog opens the native picker limited to images/video and
 * returns ready-to-insert inline HTML for the note body ("" when cancelled).
 */
export function AttachMediaViaDialog(noteID: number): $CancellablePromise<string> {
    return $Call.ByID(2425229857, noteID);
}

/**
 * AttachPath copies a known path (drag & drop from the OS gives real paths).
 */
export function AttachPath(noteID: number, path: string): $CancellablePromise<$models.Attachment | null> {
    return $Call.ByID(81366466, noteID, path);
}

/**
 * AttachViaDialog opens the native file picker and copies the chosen file
 * into the note's attachment store. Returns nil (no error) when cancelled.
 */
export function AttachViaDialog(noteID: number): $CancellablePromise<$models.Attachment | null> {
    return $Call.ByID(2744309699, noteID);
}

/**
 * List returns the attachments of a note.
 */
export function List(noteID: number): $CancellablePromise<$models.Attachment[] | null> {
    return $Call.ByID(353701020, noteID);
}

/**
 * OpenWith launches the attachment in the OS default application.
 */
export function OpenWith(id: number): $CancellablePromise<void> {
    return $Call.ByID(2699363436, id);
}

/**
 * Remove deletes an attachment row and its stored file.
 */
export function Remove(id: number): $CancellablePromise<void> {
    return $Call.ByID(2672358820, id);
}

/**
 * SaveCopyPath opens a native save dialog and copies the attachment out
 * (returns the destination path). Empty string == cancelled.
 */
export function SaveCopyPath(id: number): $CancellablePromise<string> {
    return $Call.ByID(3097576783, id);
}
