// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Attachment is a file copied into the Sharknote data dir and linked to a
 * note. The stored name on disk is a random token plus the original
 * extension; the human-visible filename lives in the database.
 */
export class Attachment {
    "id": number;
    "noteId": number;
    "filename": string;
    "size": number;
    "mime": string;
    "createdAt": string;

    /** Creates a new Attachment instance. */
    constructor($$source: Partial<Attachment> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("noteId" in $$source)) {
            this["noteId"] = 0;
        }
        if (!("filename" in $$source)) {
            this["filename"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("mime" in $$source)) {
            this["mime"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Attachment instance from a string or object.
     */
    static createFrom($$source: any = {}): Attachment {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Attachment($$parsedSource as Partial<Attachment>);
    }
}

/**
 * Backlink describes a note that links to the currently open note.
 */
export class Backlink {
    "id": number;
    "title": string;
    "excerpt": string;

    /** Creates a new Backlink instance. */
    constructor($$source: Partial<Backlink> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("excerpt" in $$source)) {
            this["excerpt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Backlink instance from a string or object.
     */
    static createFrom($$source: any = {}): Backlink {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Backlink($$parsedSource as Partial<Backlink>);
    }
}

/**
 * GraphData is the full payload for the graph view.
 */
export class GraphData {
    "nodes": GraphNode[];
    "edges": GraphEdge[];

    /** Creates a new GraphData instance. */
    constructor($$source: Partial<GraphData> = {}) {
        if (!("nodes" in $$source)) {
            this["nodes"] = [];
        }
        if (!("edges" in $$source)) {
            this["edges"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GraphData instance from a string or object.
     */
    static createFrom($$source: any = {}): GraphData {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("nodes" in $$parsedSource) {
            $$parsedSource["nodes"] = $$createField0_0($$parsedSource["nodes"]);
        }
        if ("edges" in $$parsedSource) {
            $$parsedSource["edges"] = $$createField1_0($$parsedSource["edges"]);
        }
        return new GraphData($$parsedSource as Partial<GraphData>);
    }
}

/**
 * GraphEdge is a resolved bidirectional link between two notes.
 */
export class GraphEdge {
    "source": number;
    "target": number;

    /** Creates a new GraphEdge instance. */
    constructor($$source: Partial<GraphEdge> = {}) {
        if (!("source" in $$source)) {
            this["source"] = 0;
        }
        if (!("target" in $$source)) {
            this["target"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GraphEdge instance from a string or object.
     */
    static createFrom($$source: any = {}): GraphEdge {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GraphEdge($$parsedSource as Partial<GraphEdge>);
    }
}

/**
 * GraphNode is a note rendered as a node in the knowledge graph.
 */
export class GraphNode {
    "id": number;
    "title": string;
    "linkCount": number;
    "createdAt": string;
    "updatedAt": string;

    /** Creates a new GraphNode instance. */
    constructor($$source: Partial<GraphNode> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("linkCount" in $$source)) {
            this["linkCount"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GraphNode instance from a string or object.
     */
    static createFrom($$source: any = {}): GraphNode {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GraphNode($$parsedSource as Partial<GraphNode>);
    }
}

/**
 * LinkInfo describes one wiki-link found inside a note's content.
 */
export class LinkInfo {
    /**
     * 0 when the target note does not exist yet
     */
    "targetId": number;

    /**
     * resolved title, or the unresolved target text
     */
    "targetTitle": string;
    "resolved": boolean;

    /** Creates a new LinkInfo instance. */
    constructor($$source: Partial<LinkInfo> = {}) {
        if (!("targetId" in $$source)) {
            this["targetId"] = 0;
        }
        if (!("targetTitle" in $$source)) {
            this["targetTitle"] = "";
        }
        if (!("resolved" in $$source)) {
            this["resolved"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LinkInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): LinkInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LinkInfo($$parsedSource as Partial<LinkInfo>);
    }
}

/**
 * Note is the full record of a note.
 */
export class Note {
    "id": number;
    "title": string;
    "content": string;
    "createdAt": string;
    "updatedAt": string;
    "starred": boolean;

    /** Creates a new Note instance. */
    constructor($$source: Partial<Note> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "";
        }
        if (!("starred" in $$source)) {
            this["starred"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Note instance from a string or object.
     */
    static createFrom($$source: any = {}): Note {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Note($$parsedSource as Partial<Note>);
    }
}

/**
 * NoteSummary is the lightweight record used for lists and search results.
 */
export class NoteSummary {
    "id": number;
    "title": string;
    "excerpt": string;
    "createdAt": string;
    "updatedAt": string;
    "starred": boolean;

    /** Creates a new NoteSummary instance. */
    constructor($$source: Partial<NoteSummary> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("excerpt" in $$source)) {
            this["excerpt"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "";
        }
        if (!("starred" in $$source)) {
            this["starred"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NoteSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): NoteSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NoteSummary($$parsedSource as Partial<NoteSummary>);
    }
}

/**
 * SaveNoteResult reports where a "Save as…" write landed. SavedPath is empty
 * when the user cancelled the dialog.
 */
export class SaveNoteResult {
    "savedPath": string;

    /** Creates a new SaveNoteResult instance. */
    constructor($$source: Partial<SaveNoteResult> = {}) {
        if (!("savedPath" in $$source)) {
            this["savedPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SaveNoteResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SaveNoteResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SaveNoteResult($$parsedSource as Partial<SaveNoteResult>);
    }
}

/**
 * Settings is the user-customizable application configuration. The frontend
 * treats it as one opaque bundle: it loads it at startup, applies it to the
 * UI, and persists it back with UpdateSettings whenever the user changes
 * anything in the settings dialog.
 */
export class Settings {
    /**
     * Theme controls the overall color scheme: "dark" or "light".
     */
    "theme": string;

    /**
     * Accent is the hue used across the whole UI: violet | sky | emerald |
     * amber | rose. The frontend maps it to CSS oklch hue values.
     */
    "accent": string;

    /**
     * GraphTheme picks the palette of the knowledge graph canvas:
     * crimson | violet | ocean | forest | amber.
     */
    "graphTheme": string;

    /**
     * EditorFont is the typeface of the note body: serif | sans | mono.
     */
    "editorFont": string;

    /**
     * EditorFontSize is the note body font size in pixels (13–19).
     */
    "editorFontSize": number;

    /**
     * DefaultView decides whether notes open in preview or edit mode.
     */
    "defaultView": string;

    /**
     * AutosaveDelay is the debounce (ms) between typing and saving.
     */
    "autosaveDelay": number;

    /**
     * ConfirmDelete asks for confirmation before deleting a note.
     */
    "confirmDelete": boolean;

    /**
     * ShowMdExtension appends ".md" to new note titles so notes look like
     * markdown files (e.g. "Meeting notes.md"). Existing notes are never
     * renamed, and a title that already ends in .md is left alone.
     */
    "showMdExtension": boolean;

    /**
     * VaultPath is the last folder opened with "Open folder". Empty when
     * the user has never opened a folder.
     */
    "vaultPath": string;

    /** Creates a new Settings instance. */
    constructor($$source: Partial<Settings> = {}) {
        if (!("theme" in $$source)) {
            this["theme"] = "";
        }
        if (!("accent" in $$source)) {
            this["accent"] = "";
        }
        if (!("graphTheme" in $$source)) {
            this["graphTheme"] = "";
        }
        if (!("editorFont" in $$source)) {
            this["editorFont"] = "";
        }
        if (!("editorFontSize" in $$source)) {
            this["editorFontSize"] = 0;
        }
        if (!("defaultView" in $$source)) {
            this["defaultView"] = "";
        }
        if (!("autosaveDelay" in $$source)) {
            this["autosaveDelay"] = 0;
        }
        if (!("confirmDelete" in $$source)) {
            this["confirmDelete"] = false;
        }
        if (!("showMdExtension" in $$source)) {
            this["showMdExtension"] = false;
        }
        if (!("vaultPath" in $$source)) {
            this["vaultPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     */
    static createFrom($$source: any = {}): Settings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Settings($$parsedSource as Partial<Settings>);
    }
}

/**
 * Todo is a checklist item with optional due date + alarm time.
 * DueAt/AlarmAt are RFC3339 UTC strings; empty when unset.
 */
export class Todo {
    "id": number;

    /**
     * 0 = global inbox
     */
    "noteId": number;
    "text": string;
    "done": boolean;
    "dueAt": string;
    "alarmAt": string;
    "alarmFired": boolean;
    "createdAt": string;
    "completedAt": string;

    /** Creates a new Todo instance. */
    constructor($$source: Partial<Todo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("noteId" in $$source)) {
            this["noteId"] = 0;
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("done" in $$source)) {
            this["done"] = false;
        }
        if (!("dueAt" in $$source)) {
            this["dueAt"] = "";
        }
        if (!("alarmAt" in $$source)) {
            this["alarmAt"] = "";
        }
        if (!("alarmFired" in $$source)) {
            this["alarmFired"] = false;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }
        if (!("completedAt" in $$source)) {
            this["completedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Todo instance from a string or object.
     */
    static createFrom($$source: any = {}): Todo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Todo($$parsedSource as Partial<Todo>);
    }
}

/**
 * UpdateInfo is returned to the frontend by CheckForUpdate.
 */
export class UpdateInfo {
    "available": boolean;

    /**
     * the running version
     */
    "version": string;

    /**
     * the newest published version
     */
    "latest": string;
    "notes"?: string;

    /**
     * Ready is true when a verified installer is already on disk (downloaded
     * now or in a previous session), so the UI can offer "reload" directly.
     */
    "ready": boolean;

    /** Creates a new UpdateInfo instance. */
    constructor($$source: Partial<UpdateInfo> = {}) {
        if (!("available" in $$source)) {
            this["available"] = false;
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("latest" in $$source)) {
            this["latest"] = "";
        }
        if (!("ready" in $$source)) {
            this["ready"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateInfo($$parsedSource as Partial<UpdateInfo>);
    }
}

// Private type creation functions
const $$createType0 = GraphNode.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = GraphEdge.createFrom;
const $$createType3 = $Create.Array($$createType2);
