// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Backlink describes a note that links to the currently open note.
 */
export interface Backlink {
    "id": number;
    "title": string;
    "excerpt": string;
}

/**
 * GraphData is the full payload for the graph view.
 */
export interface GraphData {
    "nodes": GraphNode[] | null;
    "edges": GraphEdge[] | null;
}

/**
 * GraphEdge is a resolved bidirectional link between two notes.
 */
export interface GraphEdge {
    "source": number;
    "target": number;
}

/**
 * GraphNode is a note rendered as a node in the knowledge graph.
 */
export interface GraphNode {
    "id": number;
    "title": string;
    "linkCount": number;
    "createdAt": string;
    "updatedAt": string;
}

/**
 * LinkInfo describes one wiki-link found inside a note's content.
 */
export interface LinkInfo {
    /**
     * 0 when the target note does not exist yet
     */
    "targetId": number;

    /**
     * resolved title, or the unresolved target text
     */
    "targetTitle": string;
    "resolved": boolean;
}

/**
 * Note is the full record of a note.
 */
export interface Note {
    "id": number;
    "title": string;
    "content": string;
    "createdAt": string;
    "updatedAt": string;
}

/**
 * NoteSummary is the lightweight record used for lists and search results.
 */
export interface NoteSummary {
    "id": number;
    "title": string;
    "excerpt": string;
    "createdAt": string;
    "updatedAt": string;
}

/**
 * SaveNoteResult reports where a "Save as…" write landed. SavedPath is empty
 * when the user cancelled the dialog.
 */
export interface SaveNoteResult {
    "savedPath": string;
}

/**
 * Settings is the user-customizable application configuration. The frontend
 * treats it as one opaque bundle: it loads it at startup, applies it to the
 * UI, and persists it back with UpdateSettings whenever the user changes
 * anything in the settings dialog.
 */
export interface Settings {
    /**
     * Theme controls the overall color scheme: "dark" or "light".
     */
    "theme": string;

    /**
     * Accent is the hue used across the whole UI: violet | sky | emerald |
     * amber | rose. The frontend maps it to CSS oklch hue values.
     */
    "accent": string;

    /**
     * GraphTheme picks the palette of the knowledge graph canvas:
     * crimson | violet | ocean | forest | amber.
     */
    "graphTheme": string;

    /**
     * EditorFont is the typeface of the note body: serif | sans | mono.
     */
    "editorFont": string;

    /**
     * EditorFontSize is the note body font size in pixels (13–19).
     */
    "editorFontSize": number;

    /**
     * DefaultView decides whether notes open in preview or edit mode.
     */
    "defaultView": string;

    /**
     * AutosaveDelay is the debounce (ms) between typing and saving.
     */
    "autosaveDelay": number;

    /**
     * ConfirmDelete asks for confirmation before deleting a note.
     */
    "confirmDelete": boolean;

    /**
     * ShowMdExtension appends ".md" to new note titles so notes look like
     * markdown files (e.g. "Meeting notes.md"). Existing notes are never
     * renamed, and a title that already ends in .md is left alone.
     */
    "showMdExtension": boolean;

    /**
     * VaultPath is the last folder opened with "Open folder". Empty when
     * the user has never opened a folder.
     */
    "vaultPath": string;
}

/**
 * UpdateInfo is returned to the frontend by CheckForUpdate.
 */
export interface UpdateInfo {
    "available": boolean;

    /**
     * the running version
     */
    "version": string;

    /**
     * the newest published version
     */
    "latest": string;
    "notes"?: string;

    /**
     * Ready is true when a verified installer is already on disk (downloaded
     * now or in a previous session), so the UI can offer "reload" directly.
     */
    "ready": boolean;
}
