// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * NoteService exposes the note store to the frontend through Wails bindings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateNote creates a note with the given title and content.
 */
export function CreateNote(title: string, content: string): $CancellablePromise<$models.Note | null> {
    return $Call.ByID(3901296041, title, content).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DeleteNote permanently removes a note and all links pointing to or from it.
 */
export function DeleteNote(id: number): $CancellablePromise<void> {
    return $Call.ByID(3639942098, id);
}

/**
 * GetBacklinks lists the notes that link to a given note.
 */
export function GetBacklinks(id: number): $CancellablePromise<$models.Backlink[]> {
    return $Call.ByID(3613702605, id).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetGraph returns every note as a node and every resolved link as an edge.
 */
export function GetGraph(): $CancellablePromise<$models.GraphData | null> {
    return $Call.ByID(3565607809).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetNote returns the full record of a single note.
 */
export function GetNote(id: number): $CancellablePromise<$models.Note | null> {
    return $Call.ByID(1276837971, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetOutgoingLinks lists the wiki links written inside a note.
 */
export function GetOutgoingLinks(id: number): $CancellablePromise<$models.LinkInfo[]> {
    return $Call.ByID(3162422950, id).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * GetSettings returns the persisted user preferences.
 */
export function GetSettings(): $CancellablePromise<$models.Settings> {
    return $Call.ByID(2084625886).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * ImportFile reads a markdown file from disk and stores it as a note. The
 * note is named after the YAML frontmatter `title` when the file has one,
 * otherwise after the filename (without extension). If a note with that title
 * already exists its content is replaced, so re-opening the same file never
 * creates duplicates.
 */
export function ImportFile(path: string): $CancellablePromise<$models.Note | null> {
    return $Call.ByID(3998441678, path).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ImportFiles imports a list of markdown files, returning the ids of the
 * notes that were created or updated (in the same order as the input).
 */
export function ImportFiles(paths: string[]): $CancellablePromise<number[]> {
    return $Call.ByID(3930147207, paths).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * ImportFolder imports every .md file under dir (recursively, skipping
 * hidden folders like .git and .obsidian), sorted by path for stable
 * ordering. Returns the ids of all imported notes.
 */
export function ImportFolder(dir: string): $CancellablePromise<number[]> {
    return $Call.ByID(2785704156, dir).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * ListNotes returns all notes, most recently updated first.
 */
export function ListNotes(): $CancellablePromise<$models.NoteSummary[]> {
    return $Call.ByID(27288930).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * OpenFiles shows a native multi-select dialog for markdown files, imports
 * the picked files, and returns the ids of the notes that were created or
 * updated. Returns nil when the user cancels.
 */
export function OpenFiles(): $CancellablePromise<number[]> {
    return $Call.ByID(1051351432).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * OpenFolderDialog shows a native folder picker, imports every markdown file
 * inside it, and remembers the folder as the current vault. Used from the
 * "Open folder" button and the Settings dialog to pick the vault path.
 */
export function OpenFolderDialog(): $CancellablePromise<number[]> {
    return $Call.ByID(2671632665).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * RenameNote changes a note's title and rewrites every [[wiki link]] that
 * pointed at the old title in other notes.
 */
export function RenameNote(id: number, title: string): $CancellablePromise<$models.Note | null> {
    return $Call.ByID(2999546831, id, title).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SaveNoteAs shows the system save dialog with the note's title as the
 * default file name and writes the note to the folder the user picks — any
 * folder they want (Documents, Downloads, Desktop, …). Returns the written
 * path, or a result with an empty path when the user cancels. The format is
 * chosen by the file extension: .md, .html or .txt.
 */
export function SaveNoteAs(id: number): $CancellablePromise<$models.SaveNoteResult | null> {
    return $Call.ByID(951930592, id).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * SearchNotes returns notes whose title or content matches the query.
 */
export function SearchNotes(query: string): $CancellablePromise<$models.NoteSummary[]> {
    return $Call.ByID(3427037650, query).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * SetPendingOpenedNote records a note id for the frontend to open on load.
 */
export function SetPendingOpenedNote(id: number): $CancellablePromise<void> {
    return $Call.ByID(2973572343, id);
}

/**
 * TakePendingOpenedNote returns the pending opened-note id (if any) and
 * clears it. Called by the frontend after initial load.
 */
export function TakePendingOpenedNote(): $CancellablePromise<number> {
    return $Call.ByID(550119356);
}

/**
 * ToggleStar flips a note's bookmarked state and returns the new value.
 */
export function ToggleStar(id: number): $CancellablePromise<boolean> {
    return $Call.ByID(2432431669, id);
}

/**
 * UpdateNote saves the title and content of a note, re-scanning its wiki links.
 */
export function UpdateNote(id: number, title: string, content: string): $CancellablePromise<$models.Note | null> {
    return $Call.ByID(163960476, id, title, content).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * UpdateSettings validates and persists the user preferences.
 */
export function UpdateSettings(settings: $models.Settings): $CancellablePromise<$models.Settings> {
    return $Call.ByID(1016301389, settings).then(($result: any) => {
        return $$createType8($result);
    });
}

// Private type creation functions
const $$createType0 = $models.Note.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.Backlink.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.GraphData.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $models.LinkInfo.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $models.Settings.createFrom;
const $$createType9 = $Create.Array($Create.Any);
const $$createType10 = $models.NoteSummary.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = $models.SaveNoteResult.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
