// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Create(noteID: number, text: string, dueAt: string, alarmAt: string): $CancellablePromise<$models.Todo | null> {
    return $Call.ByID(180949469, noteID, text, dueAt, alarmAt).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Delete(id: number): $CancellablePromise<void> {
    return $Call.ByID(1271921866, id);
}

/**
 * FireNow raises the alarm notification immediately (test/dev affordance and
 * used by the UI's "snooze fired alarm" banner to re-notify).
 */
export function FireNow(id: number): $CancellablePromise<void> {
    return $Call.ByID(1972017563, id);
}

export function List(noteID: number): $CancellablePromise<$models.Todo[]> {
    return $Call.ByID(3842981121, noteID).then(($result: any) => {
        return $$createType2($result);
    });
}

export function SetDone(id: number, done: boolean): $CancellablePromise<$models.Todo | null> {
    return $Call.ByID(614828143, id, done).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Update(id: number, text: string, dueAt: string, alarmAt: string): $CancellablePromise<$models.Todo | null> {
    return $Call.ByID(203246836, id, text, dueAt, alarmAt).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.Todo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType0);
