// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Create(noteID: number, text: string, dueAt: string, alarmAt: string): $CancellablePromise<$models.Todo | null> {
    return $Call.ByID(180949469, noteID, text, dueAt, alarmAt);
}

export function Delete(id: number): $CancellablePromise<void> {
    return $Call.ByID(1271921866, id);
}

/**
 * FireNow raises the alarm notification immediately (test/dev affordance and
 * used by the UI's "snooze fired alarm" banner to re-notify).
 */
export function FireNow(id: number): $CancellablePromise<void> {
    return $Call.ByID(1972017563, id);
}

export function List(noteID: number): $CancellablePromise<$models.Todo[] | null> {
    return $Call.ByID(3842981121, noteID);
}

export function SetDone(id: number, done: boolean): $CancellablePromise<$models.Todo | null> {
    return $Call.ByID(614828143, id, done);
}

export function Update(id: number, text: string, dueAt: string, alarmAt: string): $CancellablePromise<$models.Todo | null> {
    return $Call.ByID(203246836, id, text, dueAt, alarmAt);
}
