// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdaterService exposes remote update checks to the frontend bindings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ApplyUpdate runs the downloaded installer silently and quits the app. The
 * installer stops the running instance, swaps the files and the helper
 * relaunches Sharknote — the user's "reload".
 */
export function ApplyUpdate(): $CancellablePromise<void> {
    return $Call.ByID(2438952837);
}

/**
 * CheckForUpdate fetches the published manifest and compares it with the
 * running version. A network failure is returned as an error so the UI can
 * stay silent instead of nagging.
 */
export function CheckForUpdate(): $CancellablePromise<$models.UpdateInfo | null> {
    return $Call.ByID(596274054);
}

/**
 * CurrentVersion reports the running app version.
 */
export function CurrentVersion(): $CancellablePromise<string> {
    return $Call.ByID(2650752423);
}

/**
 * DownloadUpdate streams the published installer into a temp file, emitting
 * sharknote:update-progress events along the way, and verifies its SHA-256
 * against the manifest before declaring it ready.
 */
export function DownloadUpdate(): $CancellablePromise<void> {
    return $Call.ByID(2793849185);
}
